In [11]:
cd("..")

using LinearAlgebra
using Plots

using Pkg
Pkg.activate(".")
using SBP_operators

ArgumentError: ArgumentError: Package SBP_operators not found in current path:
- Run `import Pkg; Pkg.add("SBP_operators")` to install the SBP_operators package.


In [12]:
# Just a quick function for building the grid
function buildgrid(n)
    x = collect(range(0,stop=1,length=n+1))
    Δx = x[2]-x[1]
    n = n+1
    return n, x, Δx
end

buildgrid (generic function with 1 method)

## 2nd order

In [13]:
n, x, Δx = buildgrid(10)

u = x

∂ₓuₑ = ones(n) #The exact derivative value

∂ₓu = Dₓ(u,n,Δx)

∂ₓuₑ .- ∂ₓu

11-element Vector{Float64}:
  0.0
  0.0
  1.1102230246251565e-16
  0.0
  0.0
  2.220446049250313e-16
  2.220446049250313e-16
 -2.220446049250313e-16
 -2.220446049250313e-16
  2.220446049250313e-16
  2.220446049250313e-16

In [14]:
n, x, Δx = buildgrid(10)

u = 2x

∂ₓuₑ = 2ones(n)

∂ₓu = Dₓ(u,n,Δx)

∂ₓuₑ .- ∂ₓu

11-element Vector{Float64}:
  0.0
  0.0
  2.220446049250313e-16
  0.0
  0.0
  4.440892098500626e-16
  4.440892098500626e-16
 -4.440892098500626e-16
 -4.440892098500626e-16
  4.440892098500626e-16
  4.440892098500626e-16

In [16]:
n, x, Δx = buildgrid(10)

u = x.^2

∂ₓuₑ = 2x

∂ₓu = Dₓ(u,n,Δx)

∂ₓuₑ .- ∂ₓu

11-element Vector{Float64}:
 -0.10000000000000002
 -2.7755575615628914e-17
  1.1102230246251565e-16
 -1.1102230246251565e-16
  1.1102230246251565e-16
  2.220446049250313e-16
  4.440892098500626e-16
 -6.661338147750939e-16
 -4.440892098500626e-16
  6.661338147750939e-16
  0.10000000000000053

## 4th order

In [17]:
n, x, Δx = buildgrid(15)

u = x

∂ₓuₑ = ones(n)

∂ₓu = Dₓ(u,n,Δx,order=4)

∂ₓuₑ .- ∂ₓu

16-element Vector{Float64}:
  0.0
  0.0
 -2.220446049250313e-16
  2.220446049250313e-16
  2.220446049250313e-16
 -2.220446049250313e-16
 -4.440892098500626e-16
  2.220446049250313e-16
  6.661338147750939e-16
  0.0
  4.440892098500626e-16
 -2.220446049250313e-16
 -1.3322676295501878e-15
  9.992007221626409e-16
  2.220446049250313e-16
 -1.3322676295501878e-15

In [ ]:

n, x, Δx = buildgrid(15)

u = x.^2

∂ₓuₑ = 2x

∂ₓu = Dₓ(u,n,Δx)

∂ₓuₑ .≈ ∂ₓu


In [ ]:

n, x, Δx = buildgrid(20)

u = x.^3

∂ₓuₑ = 3x.^2

∂ₓu = Dₓ(u,n,Δx)

norm(∂ₓu .- ∂ₓuₑ)


In [ ]:

n, x, Δx = buildgrid(20)

u = x.^4

∂ₓuₑ = 4x.^3

∂ₓu = Dₓ(u,n,Δx)

∂ₓuₑ .≈ ∂ₓu

